### ISSUE TITLE
Epic: Merge freedombox-setup into Plinth

### ISSUE THREAD

**Issue by JosephKiranBabu** [freedombox/Plinth#1025]
Eliminate the need for freedombox-setup by merging its contents into Plinth. 
This enables us to consolidate all the setup steps required for setting up a FreedomBox server into one repository and sets us on the path to the following future changes:

1. Turn Plinth into a native Debian package, thus reducing friction while making releases.
1. Making Plinth more robust since testing one repository is easier.
1. Rename Plinth to freedombox-server (or freedombox-web considering we have a companion app on Android now)

The starting point for this refactoring is this patch on Debian BTS.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=873946

This epic consists of the following tasks:
- [x] Freedom-maker should mark FreedomBox images with a flag https://github.com/freedombox/freedom-maker/issues/123
- [x] Move networking script to Plinth #1026
- [x] Remove first-run step from freedombox-setup, cleanup setup steps from freedombox-setup
- [x] Remove setup step from freedombox-setup
- [x] Make the next release of Plinth without depending on freedombox-setup (using appropriate Depends and Breaks statements in Debian control file).

**Comment by SunilMohanAdapa** [comment]
This epic was not for entirely eliminating freedombox-setup but move most of its functions to Plinth.  This is now accomplished.
