### ISSUE TITLE
Network manager: roadmap

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#126]
- [ ] Show the current status of network connectivity (including IPs, subnets, gateways, DNS).
- [ ] Install network-manager as a dependency for freedombox-setup.
- [ ] Make freedombox-setup to do its configurations using nmcli instead of editing /etc/network/interfaces.
- [ ] During firstboot provide a way for the user to confirm/configure zones of each network interface.
- [ ] Test `shared` type connections.
- [ ] Add ability to configure mobile internet connections.
- [ ] Add ability to configure VPNs.
- [ ] Add IPv6 support.
- [ ] Simplify UI to hide unnecessary fields on value changes, show more descriptions etc.

**Comment by SunilMohanAdapa** [comment]
Three tasks "Show current status", "firstbot experience" and "Shared connections" are completed.

**Comment by SunilMohanAdapa** [comment]
We have #602 to track mobile broadband internet connections separately.

**Comment by SunilMohanAdapa** [comment]
#570 for managing VPN client connections.

**Comment by SunilMohanAdapa** [comment]
#323 to manage IPv6 support
