### ISSUE TITLE
Implement Card based UI

### ISSUE THREAD

**Issue by mray** [freedombox/Plinth#749]
Here are things that pop into my head in no particular order:

- [ ] use "material"-like theme as start
- [ ] make sure interface is "touch" - proof
- [ ] have a working responsive version  
- [ ] package and use the font "Lato"  #316
- [ ] apply color palette from [design manual](https://github.com/freedombox/Plinth/blob/master/static/themes/default/FreedomBox-Identity-Manual.pdf)
- [ ] restructure header as proposed in #739
- [ ] add card concept as proposed in #739
- [ ] create javascript fall-back solution
- [ ] add on-off toggles with smooth transition and indicating installing process 
- [ ] create enabled/ disabeled categories
- [ ] auto-sort cards inside categories (depending on having app-pages)
- [ ] define sensible categories for configuration cards

Whenever possible adhere to the [design manual](https://github.com/freedombox/Plinth/blob/master/static/themes/default/FreedomBox-Identity-Manual.pdf)

**Comment by SunilMohanAdapa** [comment]
@Marauderer97 , I believe the comic font was only meant to indicate the rough nature of the design.  Please keep the current font until we switch to a proper font as described in #316.  Please keep the help icon (until there is a better design for it).

**Comment by Marauderer97** [comment]
@mray Thank you! Will keep it all in mind, as I go about redesigning the UI. :smile: 
@SunilMohanAdapa I changed the font back to the original one, this is how the bar looks now:
![image](https://cloud.githubusercontent.com/assets/20185076/23621328/3fcfd1e6-02c0-11e7-9675-69e08daa3690.png)
What can I do next?

**Comment by SunilMohanAdapa** [comment]
@Marauderer97 , Please create a pull request for your change.

**Comment by Marauderer97** [comment]
@SunilMohanAdapa done. :+1:

**Comment by Marauderer97** [comment]
I am trying to replicate the design of the homepage as specified in this image:
![image](https://cloud.githubusercontent.com/assets/20185076/23757837/e6ce52b6-050d-11e7-922e-7fa93cc8a325.png)
which  will involve slight modification of the lower half of the page?
@SunilMohanAdapa Shall I go ahead?

**Comment by mray** [comment]
@Marauderer97 I assume you are working with the default boostrap theme. Maybe it makes sense to also tackle #617 before creating new UI elements. Just a thought.

**Comment by Marauderer97** [comment]
@mray Thanks for the suggestion!
I followed the discussion on the issue #617, but am not sure on what is the best way to override the twitter bootstrap, shall i create a bootstrap-customize.css or should i try the customize tool of bootstrap? Is there an even better way I can follow?

**Comment by mray** [comment]
The best solution probably is to replace/change the original less or sass files. But as we currently don't seem to preprocess css in plinth – so it might be best to override with plain css files that are in my [zip file](https://github.com/freedombox/Plinth/files/709638/new-css-and-less.zip). 
You can give it a try!

The cleanest way would probably to get a sass compiler, but afair @SunilMohanAdapa isn't thrilled to add even more dependencies...

If you like you can deal with css later, too. There is just some benefit in already seeing a more "final" look right from the start.

**Comment by Marauderer97** [comment]
@mray I agree, handling the css changes in the beginning will be beneficial. I will make a PR with the modifications in the css, once we finalise whether or not we compile with sass.
Also this is how the Home page looks now, any suggestions/comments?
![image](https://cloud.githubusercontent.com/assets/20185076/23793269/6112c83e-05b0-11e7-9924-c67b5233f8ef.png)

**Comment by mray** [comment]
Not sure how detailed the feedback needs to be at this stage so I give you all I have:

 * The Home page lacks the [panels](https://getbootstrap.com/components/#panels), which I referred to as "Cards". It is important to generally connect apps to the physical concept of cards via the visual cue. It should be like you can almost touch each app, whether disabled, enabled or on the front page.

* the title of the cards should emphasize the project name and feature the category as a second priority similar to this:
![image](https://cloud.githubusercontent.com/assets/164785/23793705/e215fbb4-058c-11e7-907e-bf2a13b4732e.png)

* the FreedomBox logo at the bottom should not compete with the other logos, so it can be noticably smaller in comparison. You can also put in some more air between apps and the FBX logo, they are a bit close. It also should be the proper logo with the correct Font as on the front page.

* there is something strange about the center alignment in the footer
* I'd probably make the javascript licence information 50% transparent / lighter – if we need to have it there at all (it is software running on my computer after all :P ).

* your header previously had text like  * home * apps * configuration  which was better

**Comment by Marauderer97** [comment]
@mray Thanks for your feedback!

The Home page lacks the panels <https://getbootstrap.com/components/#panels>,
> which I referred to as "Cards". It is important to generally connect apps
> to the physical concept of cards via the visual cue. It should be like you
> can almost touch each app, whether disabled, enabled or on the front page.

 Yes I realize this, for now I am only looking to change the footer and the
links like your design suggested. I am trying to get used to the project
and the community with small contributions initially.

I will work on the center-alignment and the logo size like you said.

> your header previously had text like * home * apps * configuration which
> was better

Yes, I have made a PR that changes the header, and am waiting for it to get
merged.

**Comment by Marauderer97** [comment]
@mray I tried incorporating your suggestions.. does it look alright?
![image](https://cloud.githubusercontent.com/assets/20185076/23823380/4eff4988-0687-11e7-82b3-0297e69f3fc7.png)

**Comment by mray** [comment]
Great! Looks much better, but a with logos there is an important thing from a design point of view: Keep the aspect ratio of images 1:1. The FreedomBox logo is too narrow.

**Comment by mray** [comment]
Oh, and "IRC Chatroom" misses a space.

**Comment by Marauderer97** [comment]
@mray What link should IRC Chatroom redirect to?

**Comment by mray** [comment]
maybe this is a good link: http://webchat.freenode.net?randomnick=1&channels=%23freedombox&uio=MTE9MjA16a

**Comment by mray** [comment]
oops no. that is actually the wrong room. is there a web ui for our room?

**Comment by jvalleroy** [comment]
We can use this link: https://webchat.oftc.net/?randomnick=1&channels=freedombox&prompt=1

**Comment by Marauderer97** [comment]
@mray Done! :smile: 
![image](https://cloud.githubusercontent.com/assets/20185076/23826143/f62681b6-06bb-11e7-93a5-f7bc35c0b3d9.png)
Should I make a PR?

**Comment by mray** [comment]
looks good!

**Comment by thekishanraval** [comment]
@Marauderer97 Can I collaborate with you on the visual design ?

**Comment by SunilMohanAdapa** [comment]
Header changes merged from #751 .

**Comment by SunilMohanAdapa** [comment]
Footer changes merged from #755 . We need to decide whether to keep the two paragraphs of the text and the link to "Javascript license information".  I haven't seen the requirements from Javascript license patch. @jvalleroy ?

**Comment by jvalleroy** [comment]
@SunilMohanAdapa The link to the JS license information page was added to (partially) support LibreJS (see #543). We might also consider mentioning Plinth's license in the footer.

**Comment by kkampardi** [comment]
@mray from witch task do you thing I could better start? What about "use "material"-like theme as start"

**Comment by mray** [comment]
@kkampardi I don't know. Maybe spending some time on  "Store more app meta-information #832" might be good? So there is everything in place and ready to grab for the interface? But actually I think you should pick first whatever you like doing most.

**Comment by kkampardi** [comment]
Well @mray the fact that Plinth is my first time working on a real application  (I mean working on something else rather than a website) makes me feel like sitting on the fence right now. That's why I'm always asking. I'll try to find my way around starting form #832 :)
